name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/grommir/zabbix-docker-notify/zabbix-docker-notify:$GITHUB_SHA
    - name: Authenticate
      run: docker login docker.pkg.github.com --username grommir
    - name: Publish
      run: docker push docker.pkg.github.com/grommir/zabbix-docker-notify/zabbix-docker-notify:$GITHUB_SHA
